name: Build docs manifest

on:
  push:
    paths:
      - 'docs/**'
      - 'build_docs_manifest.py'

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate docs.json
        run: python build_docs_manifest.py docs docs.json

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs.json
          git diff --cached --quiet || git commit -m "Auto-update docs.json [skip ci]"
          git push
